# Generated by Django 4.1.3 on 2022-11-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtype',
            options={},
        ),
    ]
